### ISSUE TITLE
DLL does not contain the BPC static methods 

### ISSUE THREAD

**Issue by voult2** [papercrane1001/-1001-WeaponsTabReborn#4]
Hey PaperCrane. It seems the code in master and the DLL in steam do not match.

The DDL in steam is missing the BPC static methods. See below:
![image](https://github.com/papercrane1001/-1001-WeaponsTabReborn/assets/5374128/4dbb41e4-e8ad-4a06-9294-abf28f726a0e)

**Comment by papercrane1001** [comment]
I know exactly what happened. I'll fix it as soon as I can.

**Comment by papercrane1001** [comment]
Fixed. Updated on both GitHub and Steam.

**Comment by voult2** [comment]
Hi again PaperCrane! Almost but not there yet :-) You updated the Assemblies/ folder with the right build DLL but you forgot to also update/copy to  the 1.4/Assemblies/ folder, which is where the game looks into.  :-)
